include Makefile.inc

PROGRAM = onvif_total_project

all: $(OBJECTS_ONVIF) $(OBJECTS_MODBUS) $(OBJECTS_WEBSERVER) $(OBJECTS_COMMAND) $(OBJECTS)
	$(CC) -o $(PROGRAM) $(OBJECTS_ONVIF) $(OBJECTS_MODBUS) $(OBJECTS_WEBSERVER) $(OBJECTS_COMMAND) $(OBJECTS) $(LDLIBS)

clean:
	rm -f $(OBJECTS_ONVIF)
	rm -f $(OBJECTS_MODBUS)
	rm -f $(OBJECTS_WEBSERVER)
	rm -f $(OBJECTS_COMMAND)
	rm -f $(OBJECTS)
	rm -f $(PROGRAM)
